# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0002_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleData',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Machine')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Module')),
            ],
        ),
    ]
