# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_remove_sampledata_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledata',
            name='machine',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='module',
            field=models.IntegerField(),
        ),
    ]
