# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20170511_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
