# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='date')),
                ('machine', models.TextField(db_column='machine', null=True)),
                ('name', models.TextField(db_column='name', null=True)),
                ('value', models.FloatField(db_column='value')),
                ('active', models.NullBooleanField(db_column='active', default=True)),
            ],
            options={
                'db_table': 'datapoints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(db_column='active', default=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('type', models.TextField(blank=True, db_column='type', null=True)),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, db_column='departmentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machines', to='hierarchy.Department')),
            ],
            options={
                'db_table': 'machines',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('url', models.TextField(db_column='url')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(db_column='active', default=True)),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('type', models.TextField(db_column='type')),
                ('input1', models.TextField(db_column='input1')),
                ('input2', models.TextField(blank=True, db_column='input2', null=True)),
                ('input3', models.TextField(blank=True, db_column='input3', null=True)),
                ('input4', models.TextField(blank=True, db_column='input4', null=True)),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(db_column='active', default=True)),
                ('machine', models.ForeignKey(db_column='machineid', on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Machine')),
            ],
            options={
                'db_table': 'parts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('label', models.TextField(db_column='label')),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(db_column='active', default=True)),
                ('department', models.ForeignKey(blank=True, db_column='departmentid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='positions', to='hierarchy.Department')),
            ],
            options={
                'db_table': 'positions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_column='timestamp')),
                ('machine', models.TextField(db_column='machine')),
                ('userName', models.TextField(db_column='username')),
                ('description', models.TextField(db_column='description')),
                ('oldValue', models.TextField(db_column='oldvalue')),
                ('newValue', models.TextField(db_column='newvalue')),
            ],
            options={
                'db_table': 'processlog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Setpoint',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('specName', models.TextField(blank=True, db_column='specname', null=True)),
                ('piTagName', models.TextField(db_column='pitagname')),
                ('lowLimit', models.TextField(blank=True, db_column='lowlimit', null=True)),
                ('highLimit', models.TextField(blank=True, db_column='highlimit', null=True)),
                ('percentage', models.NullBooleanField(db_column='percentage')),
                ('itemName', models.TextField(db_column='itemname')),
                ('groupName', models.TextField(blank=True, db_column='groupname', null=True)),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('specValue', models.TextField(blank=True, db_column='specvalue', null=True)),
                ('piTagValue', models.TextField(blank=True, db_column='pitagvalue', null=True)),
                ('piTagDate', models.DateTimeField(blank=True, db_column='pitagdate', null=True)),
                ('contains', models.NullBooleanField(db_column='contains')),
                ('active', models.NullBooleanField(db_column='active', default=True)),
                ('onSpec', models.NullBooleanField(db_column='onspec')),
                ('machine', models.ForeignKey(blank=True, db_column='machineid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.Machine')),
            ],
            options={
                'db_table': 'setpoints',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('code', models.TextField(db_column='code')),
                ('location', models.TextField(db_column='location')),
                ('createDate', models.DateTimeField(db_column='createdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(db_column='active', default=True)),
                ('directory', models.TextField(db_column='directory')),
                ('latitude', models.TextField(blank=True, db_column='latitude', default=-1, null=True)),
                ('longitude', models.TextField(blank=True, db_column='longitude', default=-1, null=True)),
                ('address', models.TextField(blank=True, db_column='address', default=-1, null=True)),
                ('modules', models.ManyToManyField(to='hierarchy.Module')),
            ],
            options={
                'db_table': 'sites',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('fileName', models.TextField(db_column='filename')),
                ('lotNumber', models.TextField(db_column='lot')),
                ('createDate', models.DateTimeField(db_column='startdate', default=django.utils.timezone.now)),
                ('modifyDate', models.DateTimeField(db_column='modifydate', default=django.utils.timezone.now)),
                ('active', models.NullBooleanField(db_column='active', default=True)),
                ('machine', models.ForeignKey(db_column='machineid', on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.Machine')),
            ],
            options={
                'db_table': 'specifications',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='position',
            field=models.ForeignKey(blank=True, db_column='positionid', null=True, on_delete=django.db.models.deletion.CASCADE, to='hierarchy.Position'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modules',
            field=models.ManyToManyField(to='hierarchy.Module'),
        ),
        migrations.AddField(
            model_name='department',
            name='modules',
            field=models.ManyToManyField(to='hierarchy.Module'),
        ),
        migrations.AddField(
            model_name='department',
            name='site',
            field=models.ForeignKey(db_column='siteid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='hierarchy.Site'),
        ),
    ]
