# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='active',
            field=models.NullBooleanField(db_column='active', default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.TextField(blank=True, db_column='address', default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='directory',
            field=models.TextField(blank=True, db_column='directory', default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.TextField(blank=True, db_column='latitude', default=''),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.TextField(blank=True, db_column='location', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.TextField(blank=True, db_column='longitude', default=''),
        ),
        migrations.AlterModelTable(
            name='data',
            table='hierarchy_datapoints',
        ),
        migrations.AlterModelTable(
            name='department',
            table='hierarchy_departments',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='hierarchy_machines',
        ),
        migrations.AlterModelTable(
            name='module',
            table='hierarchy_modules',
        ),
        migrations.AlterModelTable(
            name='part',
            table='hierarchy_parts',
        ),
        migrations.AlterModelTable(
            name='position',
            table='hierarchy_positions',
        ),
        migrations.AlterModelTable(
            name='processlog',
            table='hierarchy_processlog',
        ),
        migrations.AlterModelTable(
            name='setpoint',
            table='hierarchy_setpoints',
        ),
        migrations.AlterModelTable(
            name='site',
            table='hierarchy_sites',
        ),
        migrations.AlterModelTable(
            name='specification',
            table='hierarchy_specifications',
        ),
    ]
