# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-15 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='description',
            field=models.TextField(blank=True, db_column='description'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='machine',
            field=models.ForeignKey(db_column='machineid', on_delete=django.db.models.deletion.DO_NOTHING, to='hierarchy.Machine'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='userName',
            field=models.TextField(blank=True, db_column='username'),
        ),
    ]
