# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20161119_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='site',
            name='location',
            field=models.TextField(blank=True, db_column='location', default='', null=True),
        ),
    ]
