# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0003_auto_20161119_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='setpoint',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='setpoint',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='createDate',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='modifyDate',
            new_name='modified',
        ),
        migrations.RemoveField(
            model_name='module',
            name='url',
        ),
    ]
