# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0005_auto_20161127_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('url', models.TextField(db_column='url')),
                ('active', models.BooleanField(db_column='active', default=True)),
            ],
            options={
                'db_table': 'hierarchy_apicalls',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='api_calls',
            field=models.ManyToManyField(to='hierarchy.ApiCall'),
        ),
    ]
