# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0007_auto_20161127_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicall',
            name='description',
            field=models.TextField(db_column='description', default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apicall',
            name='key',
            field=models.TextField(db_column='key', default='test'),
            preserve_default=False,
        ),
    ]
