# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0009_auto_20161129_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='defaultModule',
            field=models.ForeignKey(db_column='default_module', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='hierarchy.Module'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='defaultModule',
            field=models.ForeignKey(db_column='default_module', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machines', to='hierarchy.Module'),
        ),
    ]
