# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0002_auto_20170115_2007'),
        ('hierarchy', '0010_auto_20161129_2121'),
    ]

    operations = [
    ]
